"""Collect machine and runtime information for long-running training setup."""

from __future__ import annotations

import argparse
import json
import platform
import shutil
import subprocess
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


def _run(cmd: list[str]) -> str:
    try:
        return subprocess.check_output(cmd, text=True).strip()
    except Exception:
        return "unknown"


def _parse_sysctl(key: str) -> str:
    return _run(["sysctl", "-n", key])


@dataclass(slots=True)
class ProbeResult:
    timestamp_utc: str
    os: str
    python: str
    cpu_model: str
    cpu_logical_threads: int
    cpu_physical_cores: int
    apple_chip: str
    ram_gb: float
    disk_total_gb: float
    disk_free_gb: float
    gpu_model: str
    metal_version: str
    torch_version: str
    mps_available: bool
    mps_built: bool
    suggested_device: str
    suggested_batch_size: int
    suggested_num_workers: int
    suggested_prefetch_factor: int
    suggested_pin_memory: bool
    suggested_amp: bool
    suggested_torch_compile: bool
    suggested_gradient_checkpointing: bool
    warnings: list[str]


def probe() -> ProbeResult:
    total, used, free = shutil.disk_usage("/")
    mem_bytes = int(_parse_sysctl("hw.memsize") or 0)
    logical = int(_parse_sysctl("hw.logicalcpu") or 1)
    physical = int(_parse_sysctl("hw.physicalcpu") or logical)

    chip = _run(["bash", "-lc", "system_profiler SPHardwareDataType | awk -F': ' '/Chip/{print $2; exit}'"])
    gpu = _run(
        ["bash", "-lc", "system_profiler SPDisplaysDataType | awk -F': ' '/Chipset Model/{print $2; exit}'"]
    )
    metal = _run(["bash", "-lc", "system_profiler SPDisplaysDataType | awk -F': ' '/Metal/{print $2; exit}'"])

    warnings: list[str] = []
    torch_version = "not-installed"
    mps_available = False
    mps_built = False
    compile_ok = False

    try:
        import torch

        torch_version = torch.__version__
        mps_available = bool(torch.backends.mps.is_available())
        mps_built = bool(torch.backends.mps.is_built())
        compile_ok = hasattr(torch, "compile")
    except Exception as exc:
        warnings.append(f"Torch unavailable: {exc}")

    if mps_available and mps_built:
        device = "mps"
        pin_memory = False
        batch_size = 256 if mem_bytes < 64 * 1024**3 else 512
    else:
        device = "cpu"
        pin_memory = False
        batch_size = 128
        if torch_version == "not-installed":
            warnings.append("Install torch to enable MPS/CUDA accelerated training.")

    num_workers = max(1, min(physical, 12))

    if platform.python_version_tuple() >= ("3", "13", "0"):
        warnings.append("Python >=3.13 may not have stable torch wheels. Prefer Python 3.11/3.12.")

    return ProbeResult(
        timestamp_utc=datetime.now(UTC).isoformat(),
        os=f"{platform.system()} {platform.release()} ({platform.version()})",
        python=platform.python_version(),
        cpu_model=_parse_sysctl("machdep.cpu.brand_string"),
        cpu_logical_threads=logical,
        cpu_physical_cores=physical,
        apple_chip=chip,
        ram_gb=round(mem_bytes / 1024**3, 2),
        disk_total_gb=round(total / 1024**3, 2),
        disk_free_gb=round(free / 1024**3, 2),
        gpu_model=gpu,
        metal_version=metal,
        torch_version=torch_version,
        mps_available=mps_available,
        mps_built=mps_built,
        suggested_device=device,
        suggested_batch_size=batch_size,
        suggested_num_workers=num_workers,
        suggested_prefetch_factor=2,
        suggested_pin_memory=pin_memory,
        suggested_amp=device in {"mps", "cuda"},
        suggested_torch_compile=compile_ok,
        suggested_gradient_checkpointing=True,
        warnings=warnings,
    )


def to_markdown(result: ProbeResult) -> str:
    payload: dict[str, Any] = asdict(result)
    rows = "\n".join(f"- **{k}**: {v}" for k, v in payload.items() if k != "warnings")
    warnings = "\n".join(f"- {w}" for w in result.warnings) or "- none"
    return (
        "# System Report\n\n"
        "Generated by `tools/system_probe.py`.\n\n"
        "## Environment\n"
        f"{rows}\n\n"
        "## Warnings\n"
        f"{warnings}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate hardware/runtime system report")
    parser.add_argument("--output", type=Path, default=Path("system_report.md"))
    parser.add_argument("--json", action="store_true", help="Print probe data as JSON")
    args = parser.parse_args()

    result = probe()

    if args.json:
        print(json.dumps(asdict(result), indent=2, ensure_ascii=True))
        return

    args.output.write_text(to_markdown(result), encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
